-- Enable the pgvector extension to work with embedding vectors
CREATE EXTENSION IF NOT EXISTS vector;

-- Table to store uploaded documents and their metadata
CREATE TABLE IF NOT EXISTS documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id TEXT NOT NULL,
  filename TEXT NOT NULL,
  pages INTEGER NOT NULL DEFAULT 0,
  chunk_count INTEGER NOT NULL DEFAULT 0,
  uploaded_at TIMESTAMPTZ DEFAULT now()
);

-- Table to store document chunks and their embeddings
CREATE TABLE IF NOT EXISTS document_chunks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id UUID REFERENCES documents(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL,
  filename TEXT NOT NULL,
  chunk_id TEXT NOT NULL,
  page_number INTEGER NOT NULL,
  content TEXT NOT NULL,
  embedding vector(384),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create conversations table
CREATE TABLE IF NOT EXISTS conversations (
  id TEXT PRIMARY KEY, -- We'll use the ID generated by the frontend
  session_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT 'New Chat',
  document_id UUID REFERENCES documents(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create chat messages table
CREATE TABLE IF NOT EXISTS chat_messages (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  conversation_id TEXT REFERENCES conversations(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  message TEXT NOT NULL,
  sources JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Create Indexes for Performance ──────────────────────────────────────────

-- pgvector HNSW Index on chunks
CREATE INDEX IF NOT EXISTS document_chunks_embedding_hnsw_idx 
ON document_chunks USING hnsw (embedding vector_cosine_ops);

-- Index session_id for documents lookup
CREATE INDEX IF NOT EXISTS idx_documents_session_id ON documents(session_id);

-- Composite index for similarity search filter
CREATE INDEX IF NOT EXISTS idx_document_chunks_session_filename ON document_chunks(session_id, filename);

-- Index conversations session_id
CREATE INDEX IF NOT EXISTS idx_conversations_session_id ON conversations(session_id);

-- Index chat messages conversation_id
CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation_id ON chat_messages(conversation_id);


-- ── Auto-Update updated_at Trigger ──────────────────────────────────────────

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_conversations_updated_at ON conversations;
CREATE TRIGGER trg_update_conversations_updated_at
BEFORE UPDATE ON conversations
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- ── Row Level Security (RLS) ────────────────────────────────────────────────

ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- Policies to allow operations where session_id matches the x-session-id header
-- (PostgREST automatically exposes headers under current_setting('request.headers'))
-- Since the backend uses service_role key, these policies will not restrict backend requests.

DROP POLICY IF EXISTS "Allow documents access by session_id" ON documents;
CREATE POLICY "Allow documents access by session_id" ON documents
  FOR ALL USING (session_id = COALESCE(current_setting('request.headers', true)::json->>'x-session-id', ''))
  WITH CHECK (session_id = COALESCE(current_setting('request.headers', true)::json->>'x-session-id', ''));

DROP POLICY IF EXISTS "Allow document_chunks access by session_id" ON document_chunks;
CREATE POLICY "Allow document_chunks access by session_id" ON document_chunks
  FOR ALL USING (session_id = COALESCE(current_setting('request.headers', true)::json->>'x-session-id', ''))
  WITH CHECK (session_id = COALESCE(current_setting('request.headers', true)::json->>'x-session-id', ''));

DROP POLICY IF EXISTS "Allow conversations access by session_id" ON conversations;
CREATE POLICY "Allow conversations access by session_id" ON conversations
  FOR ALL USING (session_id = COALESCE(current_setting('request.headers', true)::json->>'x-session-id', ''))
  WITH CHECK (session_id = COALESCE(current_setting('request.headers', true)::json->>'x-session-id', ''));

DROP POLICY IF EXISTS "Allow chat_messages access by session_id" ON chat_messages;
CREATE POLICY "Allow chat_messages access by session_id" ON chat_messages
  FOR ALL USING (session_id = COALESCE(current_setting('request.headers', true)::json->>'x-session-id', ''))
  WITH CHECK (session_id = COALESCE(current_setting('request.headers', true)::json->>'x-session-id', ''));


-- ── Similarity Search RPC ───────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION match_document_chunks (
  query_embedding vector(384),
  match_count int DEFAULT 5,
  p_session_id text DEFAULT NULL,
  p_filename text DEFAULT NULL
) RETURNS TABLE (
  id UUID,
  chunk_id TEXT,
  content TEXT,
  page_number INTEGER,
  filename TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    dc.id,
    dc.chunk_id,
    dc.content,
    dc.page_number,
    dc.filename,
    1 - (dc.embedding <=> query_embedding) AS similarity
  FROM document_chunks dc
  WHERE
    (p_session_id IS NULL OR dc.session_id = p_session_id)
    AND (p_filename IS NULL OR dc.filename = p_filename)
  ORDER BY dc.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;
